# Generated by Django 3.2.4 on 2021-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conroom_reserve_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='additional_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
